### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by slayer** [gravitational/teleconsole#12]
Hi guys
First at all - thanks for a such great product

I have trouble with compiling on arm64 device (odroid c2)
```

~/go/src/github.com/gravitational/teleconsole $ go build
# github.com/gravitational/teleport/vendor/github.com/kr/pty
../teleport/vendor/github.com/kr/pty/pty_linux.go:34: undefined: _C_uint
../teleport/vendor/github.com/kr/pty/pty_linux.go:43: undefined: _C_int
# github.com/gravitational/teleport/vendor/github.com/boltdb/bolt
../teleport/vendor/github.com/boltdb/bolt/db.go:85: undefined: maxMapSize
../teleport/vendor/github.com/boltdb/bolt/db.go:85: invalid array bound maxMapSize
```

Can you help ? 
Thanks

**Comment by kontsevoy** [comment]
@slayer The issue is that Teleport (teleconsole dependency) has changed. I will update the dependencies and vendor teleport into this repo.

**Comment by kontsevoy** [comment]
@slayer I am still waiting for Teleport 2.0 to come out to vendor it it. Meanwhile, you can build Teleconsole using the original Teleport version, i.e.:

```
$ cd $GOPATH/github.com/gravitational/teleport
$ git checkout v1.3.0
$ cd $GOPTATH/github.com/gravitational/teleconsole
$ make
```

**Comment by slayer** [comment]
same errors: 

     (v1.3.0) vlad@germ ~/go/src/github.com/gravitational/teleport $ cd ../teleconsole/
     master vlad@germ ~/go/src/github.com/gravitational/teleconsole $ make
     make -C version
     make[1]: Entering directory '/home/vlad/go/src/github.com/gravitational/teleconsole/version'
     make[1]: Leaving directory '/home/vlad/go/src/github.com/gravitational/teleconsole/version'
     go build -i -ldflags -w -o out/teleconsole
     # github.com/gravitational/teleport/vendor/github.com/boltdb/bolt
     ../teleport/vendor/github.com/boltdb/bolt/db.go:85: undefined: maxMapSize
     ../teleport/vendor/github.com/boltdb/bolt/db.go:85: invalid array bound maxMapSize
     # github.com/gravitational/teleport/vendor/github.com/kr/pty
     ../teleport/vendor/github.com/kr/pty/pty_linux.go:34: undefined: _C_uint
     ../teleport/vendor/github.com/kr/pty/pty_linux.go:43: undefined: _C_int
     Makefile:15: recipe for target 'out/teleconsole' failed
     make: *** [out/teleconsole] Error 2

**Comment by slayer** [comment]
I can try to open ssh access to that device, is it interesting ?

**Comment by kontsevoy** [comment]
@slayer I think you're compiling with 64-bit ARM (armv7) Golang is that true? Teleport (which Teleconsole is built on top of) does not officially support armv7 builds (because Teleport's own dependencies do not build on it). 

We recommend using standard armv6 release of Go (the binary should run on ODROID C2 just fine). BTW, do you recommend ODROID? Is it stable? Thinking about replacing my aging Raspberry 1, which has been running for years on USB power with no problems.

**Comment by slayer** [comment]
@kontsevoy thanks, I will try.

I am using odroid as home server for a 2 months and does not have problems. Its pretty fast (4 64 bit cores). You can see benchmark https://www.jeffgeerling.com/blog/2016/review-odroid-c2-compared-raspberry-pi-3-and-orange-pi-plus
