### ISSUE TITLE
Command line option `-i` is overloaded.

### ISSUE THREAD

**Issue by daveloyall** [gravitational/teleconsole#17]
Hi, this is just a "drive by" complaint.  I haven't even use teleconsole; I only read about it.

I don't like that the command line option `-i` can take either filename or a github username.

Based on https://github.com/gravitational/teleconsole/blob/0.3.1/lib/identity.go#L136-L142 ... I think that it tries to find a file first, and if it can't, then it tries to find a github username.

I don't know if this violates the [POLA][1], because the `--help` text clearly mentions the dual-personality of this command line option...  But, supposing that a user somehow doesn't know that `-i` can grab credentials from the web...  I can only imagine that the user would be VERY surprised, maybe even upset, when it goes and does just that!

Finally, consider the random, real github user named `pubkey` (sorry, user, for bringing you into this!) and a file named `pub.key` (containing Mary Smith's public key).  A single omitted character could grant access to the wrong user.  (Of course, there are also github users named `user` and `usser`!)

I'll run along now.  In general, the 'grant access to a github user' is a great feature, keep up the good work!

[1]: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by kontsevoy** [comment]
@daveloyall the idea was to give `-i` a "path to the key". maybe a clear expression of that would be to take a url, i.e. `https://github.com/kontsevoy` or `file://kontsevoy.pub`?

It's just creating a separate flag based on where the key is would be excessive.

**Comment by daveloyall** [comment]
Using a `file://` protocol prefix for a local file doesn't sound "unixy" to me.  Using it for the remote resource sounds correct.

**Comment by kontsevoy** [comment]
after asking folks and lots of head-scratching we're leaving it as-is, 99% of the time. Besides, the goal of Teleconsole was originally to reduce configuration to a minimum and be as dumb as possible. For a more formal approach, we have Teleport with its OpenSSH CLI compatibility, etc.
