### ISSUE TITLE
Hand-shaking with public keys + GitHub flow

### ISSUE THREAD

**Issue by henvic** [gravitational/teleconsole#2]
One killer feature imho would be supporting hand-shaking with a private / public key scheme. To make things even better, what about this:
1. I say I am someone, say, @henvic, on GitHub by typing "teleconsole login henvic"
2. I try to join a session by someone else
3. this someone else sees "GitHub user @henvic has requested to join. Allow? [y/n]" (see #1)

This can easily be done with https://developer.github.com/v3/users/keys/

When I try to do "teleconsole login" it should test if I have any keys associated with the given user.

Nice tool. Congratulations.

**Comment by kontsevoy** [comment]
The latest release implements exactly this.
