### ISSUE TITLE
Connecting behind a proxy

### ISSUE THREAD

**Issue by victorbrca** [gravitational/teleconsole#25]
Has anyone had any luck connecting to teleconsole behind a corporate proxy? I have even tried by setting 'http_proxy' and 'https_proxy', however I'm not able to. 

Thanks,
Victor.

**Comment by kontsevoy** [comment]
@victorbrca Teleconsole is 99% based on Teleport. The support for `http_proxy` and `https_proxy` is coming up in Teleport 2.1 (about a month out)
