### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by marcinciarka** [gravitational/teleconsole#4]
Is there or will where be a Windows version?

**Comment by kontsevoy** [comment]
@dreszczyk Teleconsole is based on [Teleport](https://gravitational.com/teleport/) which does not support Windows (in part because its own 3rd party dependencies do not support Windows) so we're at the end of a long chain here... Closing for now.

**Comment by cyparu** [comment]
With Teleport Client (tsh) now working also on Windows (ex: https://gravitational.com/teleport/download ) is it possible to also support teleconsole on Windows ?

**Comment by kontsevoy** [comment]
@cyparu `tsh` only implements the "login" command which retreives a certificate and stores it in the SSH agent. It can't do a proper SSH session on Windows, and, by extension, neither can Teleconsole :(
