### ISSUE TITLE
terminal size

### ISSUE THREAD

**Issue by kisst** [gravitational/teleconsole#46]
Not sure this is just undocumented, independent from the project or just simple a limitation, but I'm wondering if it's possible to choose the size, the default is width = 80 height = 25, which is not much, how would I go around to increase that ?

**Comment by kontsevoy** [comment]
@kisst not sure what do you mean... can you just resize the window? I am aware of a bug which currently doesn't allow the web UI to update it's size on startup (so it forces everything to "shrink" to 80x25) but this will be fixed soon.

For now, just resize the terminal if you want a bigger window.
