### ISSUE TITLE
Specify teleconsole local listening port

### ISSUE THREAD

**Issue by el-psycho** [gravitational/teleconsole#49]
Is there a way to specify what port(s) teleconsole should listen on? after running `# teleconsole`
random ports are used. For example: 
```
# netstat -ntlup | grep -i teleconsole
tcp        0      0 127.0.0.1:43119         0.0.0.0:*               LISTEN      1461/teleconsole    
tcp        0      0 127.0.0.1:44529         0.0.0.0:*               LISTEN      1461/teleconsole    
tcp        0      0 127.0.0.1:36695         0.0.0.0:*               LISTEN      1461/teleconsole    
tcp        0      0 127.0.0.1:33596         0.0.0.0:*               LISTEN      1461/teleconsole
```

It would be very handy for systems with firewalls active to be able to always start teleconsole with specific ports so they can be allowed through the firewall.

**Comment by kontsevoy** [comment]
@el-psycho When joining a session, Teleconsole does not listen to anything. When starting a session, Teleconsole only listens on your local AKA `lo` interface (that's how Teleport works, the library it's based on) so it's not reachable from other computers so firewalls should not be a concern.

Does this make sense? I hope I answered your question.
