### ISSUE TITLE
scp through teleconsole

### ISSUE THREAD

**Issue by jchwenger** [gravitational/teleconsole#64]
Hi,

I can't seem to find documentation on copying/transferring file over teleconsole. Is it possible? What I mean is simply copy files from/to the computers connected by the teleconsole session. I can imagine that this behaviour is meant not to be possible, I just don't find an answer to it.

Any help would be welcome, thank you!

**Comment by webvictim** [comment]
Indeed you're right, this isn't possible with teleconsole.

**Comment by jchwenger** [comment]
Thanks for this info.
